-- 시퀀스 삭제
DROP SEQUENCE SEQ_CATEGORY_CODE;
DROP SEQUENCE SEQ_PRODUCT_CODE;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_CATEGORY_CODE;
CREATE SEQUENCE SEQ_PRODUCT_CODE;
---- 테이블 삭제
DROP TABLE TBL_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE TBL_PRODUCT CASCADE CONSTRAINTS;


-- CATEGORY테이블 생성
CREATE TABLE TBL_CATEGORY
(
   CATEGORY_CODE NUMBER NOT NULL,
   CATEGORY_NAME VARCHAR2(30) NOT NULL
);

-- 칼럼 이름 생성
COMMENT ON COLUMN TBL_CATEGORY.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN TBL_CATEGORY.CATEGORY_NAME IS '카테고리이름';

-- 인덱스 생성
CREATE UNIQUE INDEX INDEX_CATEGORY_CODE ON TBL_CATEGORY
(CATEGORY_CODE);

-- 제약조건 생성
ALTER TABLE TBL_CATEGORY
 ADD CONSTRAINT PK_CATEGORY_CODE PRIMARY KEY(CATEGORY_CODE)
 USING INDEX INDEX_CATEGORY_CODE;

-- PRODUCT테이블 생성
CREATE TABLE TBL_PRODUCT
(
  PRODUCT_CODE NUMBER NOT NULL,
  PRODUCT_NAME VARCHAR2(100) NOT NULL,
  PRODUCT_INTEREST_RATE NUMBER NOT NULL,
  CATEGORY_CODE NUMBER NOT NULL,
  PRODUCT_PERIOD_YEAR NUMBER,
  PRODUCT_AGE NUMBER,
  PRODUCT_PRICE NUMBER
);

COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_CODE IS '상품코드';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_NAME IS '상품이름';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_INTEREST_RATE IS '상품이율(%)';
COMMENT ON COLUMN TBL_PRODUCT.CATEGORY_CODE IS '카테고리코드';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_PERIOD_YEAR IS '상품가입기간(년)';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_AGE IS '상품가입나이';
COMMENT ON COLUMN TBL_PRODUCT.PRODUCT_PRICE IS '상품액수(만원)';

CREATE UNIQUE INDEX INDEX_PRODUCT_CODE ON TBL_PRODUCT
(PRODUCT_CODE);

ALTER TABLE TBL_PRODUCT
ADD CONSTRAINT PK_PRODUCT_CODE PRIMARY KEY (PRODUCT_CODE)
USING INDEX INDEX_PRODUCT_CODE;

ALTER TABLE TBL_PRODUCT
 ADD CONSTRAINT FK_CATEGORY_CODE FOREIGN KEY ( CATEGORY_CODE )
 REFERENCES TBL_CATEGORY (CATEGORY_CODE);

-- TBL_CATEGORY
INSERT INTO TBL_CATEGORY VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '예금');
INSERT INTO TBL_CATEGORY VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '적금');
INSERT INTO TBL_CATEGORY VALUES (SEQ_CATEGORY_CODE.NEXTVAL, '대출');

----------- TBL_PRODUCT 은행별 예금-------------------
-- 우리은행                                                                이율, 코드, 기간, 나이, 액수
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 첫거래 예금', 7.11, 1, 3, NULL, 2000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 정기예금', 5.35, 1, 1, 20, 1000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 WON플러스 예금', 3.31, 1, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 우리어린이통장 예금', 3.35, 1, 1, 14, 300);
-- 카카오
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 첫거래 예금', 8.35, 1, 3, NULL, 1500);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 정기예금', 4.44, 1, 1, 21, 1500);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 자유예금', 3.3, 1, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 어린이통장 예금', 4.5, 1, 1, 15, 200);
-- 국민은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 첫거래 예금', 8.1, 1, 3, NULL, 1500);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 정기예금', 5.2, 1, 1, 20, 500);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 내맘대로예금', 1.91, 1, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 어린이통장 예금', 5.05, 1, 1, 13, 100);
-- 농협은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 첫거래 예금', 8.75, 1, 3, NULL, 1000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 정기예금', 4.55, 1, 1, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 자유예금', 2.21, 1, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 어린이통장 예금', 3.37, 1, 1, 15, 300);

----------- TBL_PRODUCT 은행별 적금-------------------
-- 우리은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 첫거래 적금', 7.01, 2, 3, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 정기적금', 5.03, 2, 1, 20, 100);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 WON플러스 적금', 2.5, 2, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 우리어린이통장 적금', 3.7, 1, 1, 14, 300);
-- 카카오
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 첫거래 적금', 8.35, 2, 3, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 정기적금', 3.31, 2, 1, 21, 200);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 자유적금', 2.5, 2, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 어린이통장 적금', 4.7, 2, 1, 15, 200);
-- 국민은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 첫거래 적금', 8.31, 2, 3, NULL, 100);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 정기적금', 4.33, 2, 1, 20, 500);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 내맘대로적금', 3.56, 2, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 어린이통장 적금', 5.5, 2, 1, 13, 100);
-- 농협은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 첫거래 적금', 8.53, 2, 3, NULL, 200);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 정기적금', 5.33, 2, 1, 20, 100);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 내맘대로적금', 8.56, 2, NULL, NULL, NULL);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 어린이통장 적금', 2.3, 2, 1, 15, 300);

----------- TBL_PRODUCT 은행별 대출-------------------
-- 우리은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 첫거래 대출', 10.78, 3, 3, 3, 5000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '우리는은행 WON플러스 대출', 17.00, 3, NULL, NULL, NULL);
-- 카카오
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 첫거래 대출', 11.03, 3, 3, 4, 4000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '카키오 WON플러스 대출', 17.01, 3, NULL, NULL, NULL);
-- 국민은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 첫거래 대출', 12.00, 3, 3, 5, 3000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '전국민은행 WON플러스 대출', 16.05, 3, NULL, NULL, NULL);
-- 농협은행
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 첫거래 대출', 13.35, 3, 3, 5, 7000);
INSERT INTO TBL_PRODUCT VALUES (SEQ_PRODUCT_CODE.NEXTVAL, '공협은행 WON플러스 대출', 15.18, 3, NULL, NULL, NULL);

COMMIT;